import RationalPullback
import NearPoleSeries

namespace Zeta5Local
open Polynomial
variable {p : ℕ} [Fact p.Prime]

lemma poleValue_eval₂ (x : ℚ_[p]) (r : ℤ) :
    (poleValue r).eval₂ (Rat.castHom ℚ_[p]) x = integerPoleValue x r := by
  simp [poleValue, integerPoleValue]

lemma localHarmonic_eq_cast (n : ℕ) : (localHarmonic n : ℚ_[p]) = (harmonic5 n : ℚ_[p]) := by
  simp [localHarmonic, harmonic5]

lemma residuePoleValue_near (Y : ℚ_[p]) (w : ℤ) (hw : (p : ℤ) ∣ w) :
    residuePoleValue Y w = localHarmonic (poleIndex (w / p)) - Y := by
  simp only [residuePoleValue, if_pos hw, integerPoleValue, localHarmonic_eq_cast]

lemma residuePoleValue_far (Y : ℚ_[p]) (w : ℤ) (hw : ¬(p : ℤ) ∣ w) :
    residuePoleValue Y w = analyticPoleValue ((w : ℚ_[p]) / (p : ℚ_[p])) := by
  simp only [residuePoleValue, if_neg hw]

/-- Distribution with the two signed poles generated by a quadratic
pullback, collected under their common residue. -/
theorem pairedPresentation_distribution {ι : Type*} (hp7 : 7 ≤ p)
    (P : ℚ[X]) (s : Finset ι) (r : ι → ℤ) (c : ι → ℚ_[p]) (x : ℚ_[p]) :
    (rationalTauFunctional P : ℚ_[p]) +
      ∑ i ∈ s, c i * (integerPoleValue x (r i) + integerPoleValue x (-(r i))) =
    (p : ℚ_[p])⁻¹ ^ 4 * ∑ a ∈ Finset.range p,
      ((rationalTauFunctional (P.comp (C (a : ℚ)+C (p : ℚ)*X)) : ℚ_[p]) +
        ∑ i ∈ s, (c i / (p : ℚ_[p])) *
          (residuePoleValue ((p : ℚ_[p])^5*x+distributionConstant p) (r i-a) +
            residuePoleValue ((p : ℚ_[p])^5*x+distributionConstant p) (-r i-a))) := by
  have h := rationalPresentation_distribution hp7 P (s ×ˢ (Finset.univ : Finset Bool))
    (fun ib => if ib.2 = true then r ib.1 else -(r ib.1)) (fun ib => c ib.1) x
  simpa only [Finset.sum_product, Fintype.sum_bool, Bool.false_eq_true, if_false, if_true,
    ← mul_add] using h

noncomputable def actualPullbackPolynomial (N h : ℕ) (A : ℚ[X]) : ℚ[X] :=
  rationalPullbackPolynomial (A / Zeta5Construction.tailDenominator N h)
    Finset.univ (Zeta5Construction.poleIndex N)
    (fun i : Fin h => A.eval (Zeta5Construction.node N i) / Zeta5Construction.poleDenominator N i)

noncomputable def actualPullbackResidue (N : ℕ) {h : ℕ} (A : ℚ[X]) (i : Fin h) : ℚ :=
  (A.eval (Zeta5Construction.node N i) / Zeta5Construction.poleDenominator N i) *
    (-((Zeta5Construction.poleIndex N i : ℚ)^4)/2)

lemma numeratorFunctional_padic_presentation (N h : ℕ) (A : ℚ[X]) (x : ℚ_[p]) :
    (Zeta5NumeratorFunctional.numeratorFunctional N h Zeta5Construction.polynomialFunctional A).eval₂
      (Rat.castHom ℚ_[p]) x =
    (rationalTauFunctional (actualPullbackPolynomial N h A) : ℚ_[p]) +
      ∑ i : Fin h, (actualPullbackResidue N A i : ℚ_[p]) *
        (integerPoleValue x (Zeta5Construction.poleIndex N i : ℤ) +
          integerPoleValue x (-(Zeta5Construction.poleIndex N i : ℤ))) := by
  rw [numeratorFunctional_pullback]
  simp only [eval₂_add, eval₂_C, eval₂_finsetSum, eval₂_mul, poleValue_eval₂,
    actualPullbackPolynomial, actualPullbackResidue, Rat.coe_castHom]

/-- The actual μ entry, at any p-adic parameter, is exactly the sum of its
actual local rational presentations. This includes polynomial quotients,
near integer poles, and convergent far poles. -/
theorem numeratorFunctional_padic_distribution (hp7 : 7 ≤ p)
    (N h : ℕ) (A : ℚ[X]) (x : ℚ_[p]) :
    (Zeta5NumeratorFunctional.numeratorFunctional N h Zeta5Construction.polynomialFunctional A).eval₂
      (Rat.castHom ℚ_[p]) x =
    (p : ℚ_[p])⁻¹ ^ 4 * ∑ a ∈ Finset.range p,
      ((rationalTauFunctional ((actualPullbackPolynomial N h A).comp
        (C (a : ℚ)+C (p : ℚ)*X)) : ℚ_[p]) +
        ∑ i : Fin h, ((actualPullbackResidue N A i : ℚ_[p]) / (p : ℚ_[p])) *
          (residuePoleValue ((p : ℚ_[p])^5*x+distributionConstant p)
            ((Zeta5Construction.poleIndex N i : ℤ)-a) +
          residuePoleValue ((p : ℚ_[p])^5*x+distributionConstant p)
            (-(Zeta5Construction.poleIndex N i : ℤ)-a))) := by
  rw [numeratorFunctional_padic_presentation]
  exact pairedPresentation_distribution hp7 _ _ _ _ x

#print axioms numeratorFunctional_padic_distribution
end Zeta5Local
